name: Build Binaries

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - uses: microsoft/setup-msbuild@v2
    
    - name: Clear local NuGet cache (workaround for failed restores on windows-latest)
      run: dotnet nuget locals all --clear
      
    - name: Build
      run: MSBuild -binaryLogger:Output\BuildAllTargets.binlog -m BuildAllTargets.proj
      
    - name: Decode signing certificate
      shell: pwsh
      run: |
        $certBytes = [System.Convert]::FromBase64String("${{ secrets.SIGN_CERT }}")
        Set-Content -Value $certBytes -Encoding Byte -Path signing_cert.pfx

    - name: Sign MSIX Bundle
      shell: pwsh
      run: |
        $bundle = Get-ChildItem -Path "Output/Binaries/AppPackages" -Filter "*.msixbundle" -Recurse | Select-Object -First 1
        if (-not $bundle) { throw "MSIX bundle not found!" }

        & "C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe" sign `
          /fd SHA256 `
          /f signing_cert.pfx `
          /p "${{ secrets.SIGN_CERT_PASSWORD }}" `
          /v $bundle.FullName
      
    - name: Upload MSIX Bundle
      uses: actions/upload-artifact@v4
      with:
        name: NanaZip_Mainline_ApplicationPackages
        path: Output/Binaries/AppPackages
        
    - name: Upload Extension Package Installer
      uses: actions/upload-artifact@v4
      with:
        name: NanaZip_Mainline_ExtensionPackageInstaller
        path: Output/NanaZip.ExtensionPackage_*.exe
        
    - name: Upload MSBuild Build Process Binary Log
      uses: actions/upload-artifact@v4
      if: '!cancelled()'
      with:
        name: NanaZip_Mainline_BuildBinaryLog
        path: Output/BuildAllTargets.binlog
